export const defaultLittleState: any = {
    name: '',
    email: '',
    phone_number: '',
    electricity_spend: '',
    price_band: '',
    additional_info: false,
    solar_load: 0,
    battery_autonomy_hours_only: 0,
    battery_autonomy_hours: 0,
    breakdowns: {},
    payment_method: 'paystack',
    name_card: '',
    card_number: '',
    expiration_date: '',
    security_code: '',
    postcode: '',
    total_cost: 0,
    business_role: "",
    finance: false,
    address_line_1: "",
    address_line_2: "",
}